# Generated by Django 3.2.4 on 2021-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='team',
            field=models.CharField(choices=[('web', 'WEB'), ('mobile', 'MOBILE'), ('design', 'DESIGN'), ('game', 'GAME'), ('marketing', 'MARKETING')], default='web', max_length=10),
        ),
    ]
