# Generated by Django 3.2.4 on 2021-07-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='start_time',
        ),
    ]
