# Generated by Django 3.2.4 on 2021-07-09 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_alter_meet_intiated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
