# Generated by Django 3.2.4 on 2021-07-09 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0005_meet_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='start_time',
        ),
    ]
