# Generated by Django 3.2.4 on 2021-07-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_remove_meet_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.DateTimeField(default='2021-07-10T00:21:37.152288Z'),
        ),
        migrations.AddField(
            model_name='meet',
            name='team',
            field=models.CharField(choices=[('web', 'WEB'), ('mobile', 'MOBILE'), ('design', 'DESIGN'), ('game', 'GAME'), ('all', 'ALL')], default='web', max_length=10),
        ),
    ]
