# Generated by Django 3.2.4 on 2021-07-20 07:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0010_alter_meet_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='team',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('web', 'WEB'), ('mobile', 'MOBILE'), ('design', 'DESIGN'), ('game', 'GAME'), ('marketing', 'MARKETING'), ('all', 'ALL')], default='design', max_length=36),
        ),
    ]
