# Generated by Django 3.2.4 on 2021-07-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210701_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='year',
        ),
    ]
