# Generated by Django 3.2.4 on 2021-07-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='year',
        ),
    ]
