# Generated by Django 3.2.4 on 2021-07-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='codechef_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='codechef_username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
