# Generated by Django 3.2.4 on 2021-07-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_newuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
