# Generated by Django 3.2.4 on 2021-07-20 07:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_newuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='expertise',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('web', 'WEB'), ('mobile', 'MOBILE'), ('design', 'DESIGN'), ('game', 'GAME'), ('marketing', 'MARKETING')], default='web', max_length=32),
        ),
    ]
